---
controller_execution_environments:
  - name: AAP Builder Stream EE
    image: quay.io/brthomps/ee-aap-ee-builder:latest
  - name: Community Terraform EE
    image: docker.io/r3dact3d/terraform-ee:1.0.2
  - name: Community General EE 
    image: docker.io/r3dact3d/ubi9-community-general:latest
  - name: Community Red Hat Insights EE
    image: quay.io/brthomps/ee_fedora_redhatinsights:latest