---
- name: Playbook to configure ansible controller post installation
  hosts: local
  vars:
    aap_hostname: "{{ lookup('env', 'CONTROLLER_HOST') }}"
    aap_validate_certs: "{{ lookup('env', 'CONTROLLER_VERIFY_SSL') | default(false) | bool }}"
    aap_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    aap_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
  collections:
    - infra.aap_configuration

  roles:
    - infra.aap_configuration.dispatch
